### ISSUE TITLE
DRY some functions

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/api.serlo.org-cache-worker#13]
@kulla 

Regarding your comment in PR #8 about unnecessary functions, I'm actually following the principle that each function should do just one thing. 
https://github.com/labs42io/clean-code-typescript#functions

For example, such a function would do itself 3 things: handle response, make retries and log.
```
      const task = this.tasks.pop()
      const { response, hasError } = await this.getResponse(task)
      if (hasError) {
        if (task.keys.length > 1) {
          this.bisect(task)
        } else if (task.numberOfRetries < MAX_RETRIES) {
          task.push({ ...task, numberOfRetries: task.numberOfRetries + 1})
        } else {
          this.errorLog.push(response)
        }
      } else {
        this.okLog.push(response)
      }
```

**Comment by hugotiburtino** [comment]
On the other hand, I'm not satisfied with my own implementation of the function and would like to improve modularity of it. I was thinking of using method chaining, so that the result would be something like:
`this.getResponse().handleResponse(bisect = true, retry = true).fillLogs()`
or even
`this.getResponse().bisect().retry().fillLogs()`

So that a future developer could easily change the code if she/he think it is best suited (v.g. one could easily get rid of retry by doing:  `this.getResponse().bisect().fillLogs()`)

**Comment by kulla** [comment]
> For example, such a function would do itself 3 things: handle response, make retries and log.

Actually it's doing one thing: Handle the result of the response (which is either bisecting the task, adding one to `numberOfRetries` or filling the task result to the log). Currently the handling of the result is distributed over different functions (`retry()` handles the  results as well as this function -> both functions call `getResponse()` and interpret its result althrough it is not necessary).

I think it is important to not overengineering the code. An example: When you have a line like `task.push({ ...task, numberOfRetries: task.numberOfRetries + 1})` it is selfexplaining enough. There is no need for a new function

```typescript
retry(task: Task) {
  task.push({ ...task, numberOfRetries: task.numberOfRetries + 1})
}
```

**Comment by kulla** [comment]
> I was thinking of using method chaining, so that the result would be something like:
> `this.getResponse().handleResponse(bisect = true, retry = true).fillLogs()`

No, without method chaining the code is also readable enough. KISS: Keep it simple stupid. It fufills the requirements. The duplication of code for handling the response and having better tests are the only things I would change now.
