### ISSUE TITLE
RFC: add code coverage badge?

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/api.serlo.org-cache-worker#7]

**Comment by inyono** [comment]
Well, if you want to include some test coverage tooling, sure. Personally, I'm not a big fan of the code coverage metric (since it doesn't say whether our tests are meaningful), but it can be helpful to locate code where additional tests might be useful.

**Comment by hugotiburtino** [comment]
Thanks for your opinion. Indeed I suppose it makes more sense to focus on meaningful tests.
I would even though implement a coverage tool, but that is not priority. So I'm going to close it for now.
